# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
 
  config.vm.network "public_network", bridge: 'en1: Wi-Fi'
 
  config.vm.define "redis" do |web|
    web.vm.box = "humaton/fedora-21-redis"
    config.vm.network "private_network", ip: "172.16.1.3"
    config.vm.network "public_network", ip: "192.168.100.1" 
  end

  config.vm.define "web" do |web|
    web.vm.box = "humaton/fedora-21-nginx"
    config.vm.network "private_network", ip: "192.168.123.3"
    config.vm.network "private_network", ip: "172.16.1.1"
    
    config.vm.provision :shell, inline: 'echo A'
  end

  config.vm.define "db" do |db|
    db.vm.box = "humaton/fedora-21-postgres"
    config.vm.network "private_network", ip: "192.168.123.4"
    config.vm.network "private_network", ip: "172.16.1.2"
    test.vm.provision :shell, inline: 'echo B'
  end

end

