# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.network :private_network, ip: "192.168.123.222"
  config.vm.box = "humaton/fedora-21-cloud"
  config.vm.host_name = "vagrant-mean"
  config.vm.synced_folder ".", "/home/vagrant/application", type: :rsync

  #provisions the environment
  config.vm.provision "ansible" do |ansible|
    ansible.raw_arguments = "-i provisioning/hosts"
    ansible.playbook = "provisioning/mean.yml"
  end
end
