# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
  end
  
  config.vm.provision "docker" do |d|
    d.run "mongo"
  end  
end
